application: writedownme
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: application.app
